### ISSUE TITLE
Change the repository name to `qiwi`

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwi#156]
Since `swift` already exist and is too popular, we decided to change the name to `qiwi`.

Full name candidates:
1. QuIqcl Widget Integration framework
2. Qt-Integrated Widget Interface
3. Others...

**Comment by choiwh03** [comment]
I'll make a new icon for `qiwi`

**Comment by BECATRUE** [comment]
I think "QuIqcl Widget Integration framework" is better since it is closer to a framework than an inteface.

**Comment by BECATRUE** [comment]
As we discussed offline, there is an enterprise namee `qiwi`, we think it would be difficult to use this name because it is even large.
Thus, we've come up with many candidates, and I think `qiwis` is the best as it is similar to `qiwi` and we can insist that its meaning is "QuIqcl Widget Integration Software".

Please leave your opinions freely! @kangz12345

**Comment by kangz12345** [comment]
Okay, then let's go with the `qiwis`!
